apiVersion: v1
kind: Service
metadata:
  name: project
  labels:
    app: project
spec:
  type: LoadBalancer
  selector:
    app: project
    deployment: ${DEPLOYMENT}
  ports:
    - port: 80
      targetPort: 8000
