apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: project-${DEPLOYMENT}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: project
        deployment: ${DEPLOYMENT}
    spec:
      containers:
        - name: project
          image: jbweber/project:${VERSION}
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
